add_lunch_combo uber_angler-user
add_lunch_combo uber_bullhead-user
add_lunch_combo uber_flo-user
add_lunch_combo uber_flounder-user
add_lunch_combo uber_hammerhead-user
add_lunch_combo uber_mako-user
add_lunch_combo uber_shamu-user
